version: "3.1"

services:

  authfull:
    container_name: authfull
    image: rodrigocipriani/authfull:0.0.1
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "3000:3000"
    # networks:
    #   - diary-network
    volumes:
      # - "./client:/home/app"
      - "./client/.env:/home/app/.env"
      - "./client/src:/home/app/src"
      - "./client/public:/home/app/public"
    working_dir: /home/app
    env_file:
      - ./client/.env.local
    # depends_on:
    #   - mongo
    #   - nginx
    #   - postgres

  # postgres:
  #   container_name: diary-postgres
  #   image: postgres:10
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - diary-network
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  # adminer:
  #   container_name: diary-adminer
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 5433:8080
  #   networks:
  #     - diary-network

# volumes:
#   mongodb:
#     #external: true
#   pgdata:

# networks:
#   diary-network:
#     driver: bridge